#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

opensmtpd_scheduler - Plugin to monitor opensmtpd_scheduler

=head1 CONFIGURATION

[opensmtpd]
env.smtpctl /usr/local/sbin/smtpctl

=head1 AUTHOR

Unknown.

=head1 LICENSE

Unknown.

=head1 MAGIC MARKERS

=begin comment

These magic markers are used by munin-node-configure when installing
munin-node.

=end comment

#%# family=auto
#%# capabilities=autoconf

=cut

SMTPCTL=${smtpctl:-"/usr/sbin/smtpctl"}

. $MUNIN_LIBDIR/plugins/plugin.sh

case $1 in
	autoconf|detect)
		if [ -f $SMTPCTL] ; then
			echo yes
			exit 0
		else
			echo "no (smtpctl not found)"
			exit 0
		fi
	;;

	config)
		echo graph_title OpenSMTPd stats 
		echo graph_vlabel mails / second
		echo graph_category opensmtpd
		echo graph_total total

		for field in permfail tempfail ok; do
			echo "$field.label $field"
			echo "$field.type DERIVE"
			print_warning $field
			print_critical $field
		done

		exit 0
	;;

esac

echo permfail.value `($SMTPCTL show stats| grep scheduler.delivery.permfail= | cut -d\= -f2)`
echo tempfail.value `($SMTPCTL show stats | grep scheduler.delivery.tempfail= | cut -d\= -f2)`
echo ok.value `($SMTPCTL show stats | grep scheduler.delivery.ok= | cut -d\= -f2)`

